# NumPy


<a id='index-1'></a>

## Contents

- [NumPy](#NumPy)  
  - [Overview](#Overview)  
  - [Introduction to NumPy](#Introduction-to-NumPy)  
  - [NumPy Arrays](#NumPy-Arrays)  
  - [Operations on Arrays](#Operations-on-Arrays)  
  - [Additional Functionality](#Additional-Functionality)  
  - [Exercises](#Exercises)  


> “Let’s be clear: the work of science has nothing whatever to do with consensus.  Consensus is the business of politics. Science, on the contrary, requires only one investigator who happens to be right, which means that he or she has results that are verifiable by reference to the real world. In science consensus is irrelevant. What is relevant is reproducible results.” – Michael Crichton

## Overview

[NumPy](https://en.wikipedia.org/wiki/NumPy) is a first-rate library for numerical programming

- Widely used in academia, finance and industry  
- Mature, fast, stable and under continuous development  


In this lecture we introduce NumPy arrays and the fundamental array processing operations provided by NumPy

### References

- [The official NumPy documentation](http://docs.scipy.org/doc/numpy/reference/)  

## Introduction to NumPy


<a id='index-2'></a>
The essential problem that NumPy solves is fast array processing

For example, suppose we want to create an array of 1 million random draws from a uniform distribution and compute the mean

If we did this in pure Python it would be orders of magnitude slower than C or Fortran

This is because

- Loops in Python over Python data types like lists carry significant overhead  
- C and Fortran code contains a lot of type information that can be used for optimization  
- Various optimizations can be carried out during compilation, when the compiler sees the instructions as a whole  


However, for a task like the one described above there’s no need to switch back to C or Fortran

Instead we can use NumPy, where the instructions look like this:

In [ ]:
import numpy as np

x = np.random.uniform(0, 1, size=1000000)
x.mean()

The operations of creating the array and computing its mean are both passed out to carefully optimized machine code compiled from C

More generally, NumPy sends operations *in batches* to optimized C and Fortran code

This is similar in spirit to Matlab, which provides an interface to fast Fortran routines

### A Comment on Vectorization

NumPy is great for operations that are naturally *vectorized*

Vectorized operations are precompiled routines that can be sent in batches, like

- matrix multiplication and other linear algebra routines  
- generating a vector of random numbers  
- applying a fixed transformation (e.g., sine or cosine) to an entire array  


In a [later lecture](numba.ipynb#) we’ll discuss code that isn’t easy to vectorize and how such routines can also be optimized


<a id='numpy-array'></a>

## NumPy Arrays


<a id='index-3'></a>
The most important thing that NumPy defines is an array data type formally called a [numpy.ndarray](http://docs.scipy.org/doc/numpy/reference/arrays.ndarray.html)

NumPy arrays power a large proportion of the scientific Python ecosystem

To create a NumPy array containing only zeros we use  [np.zeros](http://docs.scipy.org/doc/numpy/reference/generated/numpy.zeros.html#numpy.zeros)

In [1]:
a = np.zeros(3)
a

NameError: name 'np' is not defined

In [2]:
type(a)

NameError: name 'a' is not defined

NumPy arrays are somewhat like native Python lists, except that

- Data *must be homogeneous* (all elements of the same type)  
- These types must be one of the data types (`dtypes`) provided by NumPy  


The most important of these dtypes are:

- float64: 64 bit floating point number  
- int64: 64 bit integer  
- bool:  8 bit True or False  


There are also dtypes to represent complex numbers, unsigned integers, etc

On modern machines, the default dtype for arrays is `float64`

In [ ]:
a = np.zeros(3)
type(a[0])

If we want to use integers we can specify as follows:

In [ ]:
a = np.zeros(3, dtype=int)
type(a[0])


<a id='numpy-shape-dim'></a>

### Shape and Dimension


<a id='index-4'></a>
Consider the following assignment

In [ ]:
z = np.zeros(10)

Here `z` is a *flat* array with no dimension — neither row nor column vector

The dimension is recorded in the `shape` attribute, which is a tuple

In [ ]:
z.shape

Here the shape tuple has only one element, which is the length of the array (tuples with one element end with a comma)

To give it dimension, we can change the `shape` attribute

In [ ]:
z.shape = (10, 1)
z

In [ ]:
z = np.zeros(4)
z.shape = (2, 2)
z

In the last case, to make the 2 by 2 array, we could also pass a tuple to the `zeros()` function, as
in `z = np.zeros((2, 2))`


<a id='creating-arrays'></a>

### Creating Arrays


<a id='index-5'></a>
As we’ve seen, the `np.zeros` function creates an array of zeros

You can probably guess what `np.ones` creates

Related is `np.empty`, which creates arrays in memory that can later be populated with data

In [ ]:
z = np.empty(3)
z

The numbers you see here are garbage values

(Python allocates 3 contiguous 64 bit pieces of memory, and the existing contents of those memory slots are interpreted as `float64` values)

To set up a grid of evenly spaced numbers use `np.linspace`

In [ ]:
z = np.linspace(2, 4, 5)  # From 2 to 4, with 5 elements

To create an identity matrix use either `np.identity` or `np.eye`

In [ ]:
z = np.identity(2)
z

In addition, NumPy arrays can be created from Python lists, tuples, etc. using `np.array`

In [7]:
import numpy as np
z = np.array([10, 20])                 # ndarray from Python list
z

array([10, 20])

In [8]:
type(z)

numpy.ndarray

In [6]:
import numpy as np
z = np.array((10, 20), dtype=float)    # Here 'float' is equivalent to 'np.float64'
z

array([10., 20.])

In [9]:
import numpy as np
z = np.array([[1, 2], [3, 4]])         # 2D array from a list of lists
z

array([[1, 2],
       [3, 4]])

See also `np.asarray`, which performs a similar function, but does not make
a distinct copy of data already in a NumPy array

In [20]:
na = np.linspace(10, 20, 2)
na is np.asarray(na)   # Does not copy NumPy arrays

True

In [18]:
na is np.array(na)     # Does make a new copy --- perhaps unnecessarily

False

To read in the array data from a text file containing numeric data use `np.loadtxt`
or `np.genfromtxt`—see [the documentation](http://docs.scipy.org/doc/numpy/reference/routines.io.html) for details

### Array Indexing


<a id='index-6'></a>
For a flat array, indexing is the same as Python sequences:

In [21]:
z = np.linspace(1, 2, 5)
z

array([1.  , 1.25, 1.5 , 1.75, 2.  ])

In [22]:
z[0]

1.0

In [23]:
z[0:2]  # Two elements, starting at element 0

array([1.  , 1.25])

In [24]:
z[-1]

2.0

For 2D arrays the index syntax is as follows:

In [25]:
import numpy as np
z = np.array([[1, 2], [3, 4]])
z

array([[1, 2],
       [3, 4]])

In [11]:
z[0, 0]

1

In [12]:
z[0, 1]

2

And so on

Note that indices are still zero-based, to maintain compatibility with Python sequences

Columns and rows can be extracted as follows

In [13]:
z[0, :]

array([1, 2])

In [14]:
z[:, 1]

array([2, 4])

NumPy arrays of integers can also be used to extract elements

In [47]:
z = np.linspace(2, 4, 5)
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [48]:
indices = np.array((0, 2, 3)) #获取z中第0个，第2个和第3个的值
z[indices]

array([2. , 3. , 3.5])

Finally, an array of `dtype bool` can be used to extract elements

In [49]:
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [50]:
d = np.array([0, 1, 1, 0, 0], dtype=bool)
d

array([False,  True,  True, False, False])

In [51]:
#z[d]
z[z>3]

array([3.5, 4. ])

We’ll see why this is useful below

An aside: all elements of an array can be set equal to one number using slice notation

In [44]:
z = np.empty(3)
z

array([42., 42., 42.])

In [45]:
z[:] = 42
z

array([42., 42., 42.])

### Array Methods


<a id='index-7'></a>
Arrays have useful methods, all of which are carefully optimized

In [69]:
a = np.array((4, 3, 2, 1))
a

array([4, 3, 2, 1])

In [53]:
a.sort()              # Sorts a in place
a

array([1, 2, 3, 4])

In [54]:
a.sum()               # Sum

10

In [55]:
a.mean()              # Mean

2.5

In [56]:
a.max()               # Max

4

In [57]:
a.argmax()            # Returns the index of the maximal element

3

In [58]:
a.cumsum()            # Cumulative sum of the elements of a

array([ 1,  3,  6, 10], dtype=int32)

In [59]:
a.cumprod()           # Cumulative product of the elements of a

array([ 1,  2,  6, 24], dtype=int32)

In [60]:
a.var()               # Variance

1.25

In [61]:
a.std()               # Standard deviation

1.118033988749895

In [62]:
a.shape = (2, 2)
a.T                   # Equivalent to a.transpose()

array([[1, 3],
       [2, 4]])

Another method worth knowing is `searchsorted()`

If `z` is a nondecreasing array, then `z.searchsorted(a)` returns the index of the first element of `z` that is `>= a`

In [63]:
z = np.linspace(2, 4, 5)
z

array([2. , 2.5, 3. , 3.5, 4. ])

In [66]:
z.searchsorted(3.3)

3

Many of the methods discussed above have equivalent functions in the NumPy namespace

In [70]:
a = np.array((4, 3, 2, 1))

In [71]:
np.sum(a)

10

In [72]:
np.mean(a)

2.5

## Operations on Arrays


<a id='index-8'></a>

### Arithmetic Operations

The operators `+`, `-`, `*`, `/` and `**` all act *elementwise* on arrays

In [73]:
a = np.array([1, 2, 3, 4])
b = np.array([5, 6, 7, 8])
a + b

array([ 6,  8, 10, 12])

In [74]:
a * b

array([ 5, 12, 21, 32])

We can add a scalar to each element as follows

In [75]:
a + 10

array([11, 12, 13, 14])

Scalar multiplication is similar

In [76]:
a * 10

array([10, 20, 30, 40])

The two dimensional arrays follow the same general rules

In [77]:
A = np.ones((2, 2))
B = np.ones((2, 2))
A + B

array([[2., 2.],
       [2., 2.]])

In [78]:
A + 10

array([[11., 11.],
       [11., 11.]])

In [80]:
A * B

array([[1., 1.],
       [1., 1.]])


<a id='numpy-matrix-multiplication'></a>
In particular, `A * B` is *not* the matrix product, it is an element-wise product

### Matrix Multiplication


<a id='index-9'></a>
With Anaconda’s scientific Python package based around Python 3.5 and above,
one can use the `@` symbol for matrix multiplication, as follows:

In [81]:
A = np.ones((2, 2))
B = np.ones((2, 2))
A @ B

array([[2., 2.],
       [2., 2.]])

(For older versions of Python and NumPy you need to use the [np.dot](http://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) function)

We can also use `@` to take the inner product of two flat arrays

In [82]:
A = np.array((1, 2))
B = np.array((10, 20))
A @ B

50

In fact, we can use `@` when one element is a Python list or tuple

In [83]:
A = np.array(((1, 2), (3, 4)))
A

array([[1, 2],
       [3, 4]])

In [88]:
A @ (0, 1)

array([2, 4])

Since we are postmultiplying, the tuple is treated as a column vector

### Mutability and Copying Arrays

NumPy arrays are mutable data types, like Python lists

In other words, their contents can be altered (mutated) in memory after initialization

We already saw examples above

Here’s another example:

In [89]:
a = np.array([42, 44])
a

array([42, 44])

In [90]:
a[-1] = 0  # Change last element to 0
a

array([42,  0])

Mutability leads to the following behavior (which can be shocking to MATLAB programmers…)

In [91]:
a = np.random.randn(3)
a

array([-1.27324409, -0.61410274,  1.33099941])

In [92]:
b = a
b[0] = 0.0
a

array([ 0.        , -0.61410274,  1.33099941])

What’s happened is that we have changed `a` by changing `b`

The name `b` is bound to `a` and becomes just another reference to the
array (the Python assignment model is described in more detail [later in the course](python_advanced_features.ipynb#))

Hence, it has equal rights to make changes to that array

This is in fact the most sensible default behavior!

It means that we pass around only pointers to data, rather than making copies

Making copies is expensive in terms of both speed and memory

#### Making Copies

It is of course possible to make `b` an independent copy of `a` when required

This can be done using `np.copy`

In [101]:
a = np.random.randn(3)
a

array([-0.61249898,  0.89064457, -0.85748156])

In [94]:
b = np.copy(a)
b

array([-0.06449548, -1.42863625,  1.12201609])

Now `b` is an independent copy (called a *deep copy*)

In [95]:
b[:] = 1
b

array([1., 1., 1.])

In [96]:
a

array([-0.06449548, -1.42863625,  1.12201609])

Note that the change to `b` has not affected `a`

## Additional Functionality

Let’s look at some other useful things we can do with NumPy

### Vectorized Functions


<a id='index-10'></a>
NumPy provides versions of the standard functions `log`, `exp`, `sin`, etc. that act *element-wise* on arrays

In [97]:
z = np.array([1, 2, 3])
np.sin(z)

array([0.84147098, 0.90929743, 0.14112001])

This eliminates the need for explicit element-by-element loops such as

In [98]:
n = len(z)
y = np.empty(n)
for i in range(n):
    y[i] = np.sin(z[i])

Because they act element-wise on arrays, these functions are called *vectorized functions*

In NumPy-speak, they are also called *ufuncs*, which stands for “universal functions”

As we saw above, the usual arithmetic operations (`+`, `*`, etc.) also
work element-wise, and combining these with the ufuncs gives a very large set of fast element-wise functions

In [99]:
z

array([1, 2, 3])

In [100]:
(1 / np.sqrt(2 * np.pi)) * np.exp(- 0.5 * z**2)

array([0.24197072, 0.05399097, 0.00443185])

Not all user defined functions will act element-wise

For example, passing the function `f` defined below a NumPy array causes a `ValueError`

In [102]:
def f(x):
    return 1 if x > 0 else 0

The NumPy function `np.where` provides a vectorized alternative:

In [103]:
x = np.random.randn(4)
x

array([ 1.49704344, -0.16746284, -0.15800169,  0.72607014])

In [104]:
np.where(x > 0, 1, 0)  # Insert 1 if x > 0 true, otherwise 0

array([1, 0, 0, 1])

You can also use `np.vectorize` to vectorize a given function

In [105]:
def f(x): return 1 if x > 0 else 0

f = np.vectorize(f)
f(x)                # Passing the same vector x as in the previous example

array([1, 0, 0, 1])

However, this approach doesn’t always obtain the same speed as a more carefully crafted vectorized function

### Comparisons


<a id='index-11'></a>
As a rule, comparisons on arrays are done element-wise

In [106]:
z = np.array([2, 3])
y = np.array([2, 3])
z == y

array([ True,  True])

In [107]:
y[0] = 5
z == y

array([False,  True])

In [108]:
z != y

array([ True, False])

The situation is similar for `>`, `<`, `>=` and `<=`

We can also do comparisons against scalars

In [109]:
z = np.linspace(0, 10, 5)
z

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [110]:
z > 3

array([False, False,  True,  True,  True])

This is particularly useful for *conditional extraction*

In [111]:
b = z > 3
b

array([False, False,  True,  True,  True])

In [112]:
z[b]

array([ 5. ,  7.5, 10. ])

Of course we can—and frequently do—perform this in one step

In [113]:
z[z > 3]

array([ 5. ,  7.5, 10. ])

### Subpackages

NumPy provides some additional functionality related to scientific programming
through its subpackages

We’ve already seen how we can generate random variables using np.random

In [114]:
z = np.random.randn(10000)  # Generate standard normals
y = np.random.binomial(10, 0.5, size=1000)    # 1,000 draws from Bin(10, 0.5)
y.mean()

4.923

Another commonly used subpackage is np.linalg

In [115]:
A = np.array([[1, 2], [3, 4]])

np.linalg.det(A)           # Compute the determinant

-2.0000000000000004

In [116]:
np.linalg.inv(A)           # Compute the inverse

array([[-2. ,  1. ],
       [ 1.5, -0.5]])


<a id='index-13'></a>
Much of this functionality is also available in [SciPy](http://www.scipy.org/), a collection of modules that are built on top of NumPy

We’ll cover the SciPy versions in more detail [soon](scipy.ipynb#)

For a comprehensive list of what’s available in NumPy see [this documentation](https://docs.scipy.org/doc/numpy/reference/routines.html)

## Exercises


<a id='np-ex1'></a>

### Exercise 1

Consider the polynomial expression


<a id='equation-np-polynom'></a>
<table width=100%><tr style='background-color: #FFFFFF !important;'>
<td width=10%></td>
<td width=80%>
$$
p(x) = a_0 + a_1 x + a_2 x^2 + \cdots a_N x^N = \sum_{n=0}^N a_n x^n
$$
</td><td width=10% style='text-align:center !important;'>
(1)
</td></tr></table>

[Earlier](python_essentials.ipynb#pyess-ex2), you wrote a simple function `p(x, coeff)` to evaluate [(1)](#equation-np-polynom) without considering efficiency

Now write a new function that does the same job, but uses NumPy arrays and array operations for its computations, rather than any form of Python loop

(Such functionality is already implemented as `np.poly1d`, but for the sake of the exercise don’t use this class)

- Hint: Use `np.cumprod()`  



<a id='np-ex2'></a>

### Exercise 2

Let `q` be a NumPy array of length `n` with `q.sum() == 1`

Suppose that `q` represents a [probability mass function](https://en.wikipedia.org/wiki/Probability_mass_function)

We wish to generate a discrete random variable $ x $ such that $ \mathbb P\{x = i\} = q_i $

In other words, `x` takes values in `range(len(q))` and `x = i` with probability `q[i]`

The standard (inverse transform) algorithm is as follows:

- Divide the unit interval $ [0, 1] $ into $ n $ subintervals $ I_0, I_1, \ldots, I_{n-1} $ such that the length of $ I_i $ is $ q_i $  
- Draw a uniform random variable $ U $ on $ [0, 1] $ and return the $ i $ such that $ U \in I_i $  


The probability of drawing $ i $ is the length of $ I_i $, which is equal to $ q_i $

We can implement the algorithm as follows

In [1]:
from random import uniform

def sample(q):
    a = 0.0
    U = uniform(0, 1)
    for i in range(len(q)):
        if a < U <= a + q[i]:
            return i
        a = a + q[i]

If you can’t see how this works, try thinking through the flow for a simple example, such as `q = [0.25, 0.75]`
It helps to sketch the intervals on paper

Your exercise is to speed it up using NumPy, avoiding explicit loops

- Hint: Use `np.searchsorted` and `np.cumsum`  


If you can, implement the functionality as a class called `discreteRV`, where

- the data for an instance of the class is the vector of probabilities `q`  
- the class has a `draw()` method, which returns one draw according to the algorithm described above  


If you can, write the method so that `draw(k)` returns `k` draws from `q`